---
title: "Weather Information Preferences in the United States"
subtitle: "Summary Report for the _**`r params$region`**_ Region"
author: "Author: Your Name, Jr."
date: "`r format(Sys.Date(), '%A, %B %d, %Y')`"
output:
  ioslides_presentation:
    logo: images/sunstar.png
params:
  region: Pacific
---

```{r, echo=FALSE, message=FALSE, warning=FALSE }
knitr::read_chunk("code/setup.R")
```

```{r setupz, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r loadData}
```

```{r child="text/backgroundSection.Rmd"}
```

```{r child="text/purposeSection.Rmd"}
```

## Demographics of Survey Respondents in a Merged Table

This section provides demographic summary tables for the `r nrow(sdat)` survey respondents.

```{r maketable, code=readLines("code/makeTable.R")}
```

## Weather Source Preference by Gender

Finally, here is a breakdown of the `r nrow(sdat)` survey respondents for the `r params$region` region of the US on how they check their daily weather by gender.

```{r}
knitr::read_chunk("code/makeChart.R")
```

```{r makeCharts}
```
